mdadm: fix compilation errors for unused variables with GCC 16
In upcoming gcc 16, increments and assignments don't count as "uses",
causing errors like this:

Assemble.c: In function 'Assemble':
Assemble.c:1379:55: error: variable 'replcnt' set but not used [-Werror=unused-but-set-variable=]
 1379 |         unsigned int okcnt, sparecnt, rebuilding_cnt, replcnt, journalcnt;
      |                                                       ^~~~~~~

See the porting to for more details: https://gcc.gnu.org/gcc-16/porting_to.html

Signed-off-by: Martin Wilck <mwilck@suse.com>