super-intel: fix compilation error
Fix compilation error:

super-intel.c: In function ‘end_migration’:
super-intel.c:4360:29: error: writing 2 bytes into a region
			of size 0 [-Werror=stringop-overflow=]
 4360 |         dev->vol.migr_state = 0;
      |         ~~~~~~~~~~~~~~~~~~~~^~~
cc1: note: destination object is likely at address zero
cc1: all warnings being treated as errors
make: *** [Makefile:232: super-intel.o] Error 1

reported, when GCC 14 is used. Return when dev is NULL, to avoid it.

Signed-off-by: Kinga Stefaniuk <kinga.stefaniuk@intel.com>