mdadm: give more time to wait sync thread to reap
01r5fail case reports error sometimes:
++ '[' -n '2248 / 35840' ']'
++ die 'resync or recovery is happening!'
++ echo -e '\n\tERROR: resync or recovery is happening! \n'

    ERROR: resync or recovery is happening!

sync thread is reapped in md_thread. So we need to give more time to
wait sync thread to reap.

Signed-off-by: Xiao Ni <xni@redhat.com>